// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "wallpaper_api/wallpaper_manager_impl.h"

#include <utility>
#include <vector>

#include "base/android/jni_android.h"
#include "base/android/jni_array.h"
#include "base/android/jni_util.h"
#include "base/android/scoped_java_ref.h"
#include "base/logging.h"
#include "base/memory/weak_ptr.h"
#include "mojo/public/cpp/bindings/pending_receiver.h"
#include "mojo/public/cpp/bindings/remote_set.h"

// Auto-generated JNI header from WallpaperHelper.java.
// Declares:
//   Java_WallpaperHelper_create()         — bridge to Java static factory
//   Java_WallpaperHelper_destroy()        — bridge to Java destroy()
//   Java_WallpaperHelper_getWallpaperColors() — bridge to Java getter
//   JNI_WallpaperHelper_OnColorsChanged() — extern "C" callback (defined below)
//
// Java class: org.chromium.chrome.browser.wallpaper.WallpaperHelper
// Generated by jni_generator during the Chromium build.
#include "chrome/browser/wallpaper/java/jni/WallpaperHelper_jni.h"

namespace wallpaper {

namespace {

// Sentinel Java uses for absent optional colors.
constexpr int kAbsentColor = -1;

mojom::WallpaperColorsPtr BuildWallpaperColors(int primary_color,
                                               int secondary_color,
                                               int tertiary_color,
                                               int color_hints) {
  if (primary_color == kAbsentColor)
    return nullptr;

  auto colors = mojom::WallpaperColors::New();
  colors->primary_color = static_cast<uint32_t>(primary_color);
  colors->secondary_color =
      secondary_color != kAbsentColor
          ? absl::optional<uint32_t>(static_cast<uint32_t>(secondary_color))
          : absl::nullopt;
  colors->tertiary_color =
      tertiary_color != kAbsentColor
          ? absl::optional<uint32_t>(static_cast<uint32_t>(tertiary_color))
          : absl::nullopt;
  colors->color_hints = color_hints;
  return colors;
}

}  // namespace

// WallpaperManagerImpl -------------------------------------------------------

// static
void WallpaperManagerImpl::Create(
    mojo::PendingReceiver<mojom::WallpaperManager> receiver) {
  auto* impl = new WallpaperManagerImpl();
  impl->receiver_.Bind(std::move(receiver));
  // Self-delete on disconnect — long-lived Mojo service.
  impl->receiver_.set_disconnect_handler(
      base::BindOnce([](WallpaperManagerImpl* impl) { delete impl; },
                     base::Unretained(impl)));
}

WallpaperManagerImpl::WallpaperManagerImpl() {
  JNIEnv* env = base::android::AttachCurrentThread();

  // Create the Java WallpaperHelper which wraps android.app.WallpaperManager
  // and registers an OnColorsChangedListener.  The Java object stores our
  // native pointer so the JNI callback can route back to this instance.
  java_wallpaper_helper_.Reset(
      Java_WallpaperHelper_create(env, reinterpret_cast<intptr_t>(this)));
}

WallpaperManagerImpl::~WallpaperManagerImpl() {
  if (java_wallpaper_helper_) {
    JNIEnv* env = base::android::AttachCurrentThread();
    Java_WallpaperHelper_destroy(env, java_wallpaper_helper_);
  }
}

void WallpaperManagerImpl::GetWallpaperColors(
    GetWallpaperColorsCallback callback) {
  JNIEnv* env = base::android::AttachCurrentThread();

  // Java returns int[]{primary, secondary, tertiary, hints} or null.
  base::android::ScopedJavaLocalRef<jintArray> java_colors =
      Java_WallpaperHelper_getWallpaperColors(env, java_wallpaper_helper_);

  if (!java_colors.obj()) {
    std::move(callback).Run(nullptr);
    return;
  }

  std::vector<int> colors;
  base::android::JavaIntArrayToIntVector(env, java_colors, &colors);

  if (colors.size() != 4u) {
    std::move(callback).Run(nullptr);
    return;
  }

  std::move(callback).Run(
      BuildWallpaperColors(colors[0], colors[1], colors[2], colors[3]));
}

void WallpaperManagerImpl::AddColorChangeObserver(
    mojo::PendingRemote<mojom::WallpaperColorObserver> observer) {
  observers_.Add(std::move(observer));
}

void WallpaperManagerImpl::OnWallpaperColorsChanged(
    JNIEnv* env,
    int primary_color,
    int secondary_color,
    int tertiary_color,
    int color_hints) {
  auto colors = BuildWallpaperColors(primary_color, secondary_color,
                                     tertiary_color, color_hints);
  if (!colors)
    return;

  for (auto& observer : observers_) {
    observer->OnWallpaperColorsChanged(colors.Clone());
  }
}

}  // namespace wallpaper

// ---------------------------------------------------------------------------
// JNI callback — called from Java when the device wallpaper changes.
// Defined at file scope (outside namespace) for C linkage as required by JNI.
//
// Java declaration in WallpaperHelper.java:
//   private native void nativeOnColorsChanged(
//       int primary, int secondary, int tertiary, int hints);
//
// jni_generator maps this to JNI_WallpaperHelper_OnColorsChanged().
// The _jni.h header declares it extern "C"; we define it here.
// ---------------------------------------------------------------------------
void JNI_WallpaperHelper_OnColorsChanged(
    JNIEnv* env,
    const base::android::JavaParamRef<jobject>& caller,
    jint primary_color,
    jint secondary_color,
    jint tertiary_color,
    jint color_hints) {
  auto* impl = reinterpret_cast<wallpaper::WallpaperManagerImpl*>(
      base::android::GetNativePointerFromJavaPeer(env, caller));
  if (impl)
    impl->OnWallpaperColorsChanged(env, primary_color, secondary_color,
                                   tertiary_color, color_hints);
}
